### ISSUE TITLE
Can only see a subset of playlists "created by me"

### ISSUE THREAD

**Issue by gregbreit** [michaelherger/lms-plugin-tidal#10]
Currently, Favorites-->Playlists shows all playlists created by TIDAL or other TIDAL users that I have favorited. But it only shows a few of the playlists I have created myself.

So far, I don't see anything unique about the "created by me" that show up vs. the ones that are ignored. I'll keep investigating.

Please disregard if this is expected behavior at this point. I already forgot if the old TIDAL plugin handled "favorited" vs. "created by me" playlists differently.

Many many thanks for the rapid effort on this plugin.

**Comment by michaelherger** [comment]
I remember something like that from the MySB implementation... I see you've modified the title several times. Would the missing at least always be the same?

**Comment by gregbreit** [comment]
Yes, it appears the same playlists are missing each time.

I can see some of the TIDAL data is being cached:


*[24-02-12 17:57:22.4839] Plugins::TIDAL::API::Async::__ANON__ (496) Using
cache key
'tidal_resp:/users/185685180/favorites/playlists:countryCodeUS:limit2000'[24-02-12
17:57:22.4865] Plugins::TIDAL::API::Async::__ANON__ (507) Returning cached
data for /users/185685180/favorites/playlists?countryCode=US&limit=50*

I tried clearing the lms cache and restarting. Same result -- same
playlists show up.

Apologies for the title modifications -- at first glance, I didn't think
any of the "created by me" playlists were showing up.

**Comment by michaelherger** [comment]
I don't know whether you can even add one of your own playlists to your favourites. Could this be the case here?

I'll have to check what they are doing in their implementation.

**Comment by gregbreit** [comment]
As far as I know, there's no option to "favorite" one of my own playlists. I suppose TIDAL assumes if I created it, it must be a favorite.

In the TIDAL app, all playlists in "My Collection" are shown in a single list. Each has a subheading that reads either, "by me", "by TIDAL", or "by <username>". The latter two categories are playlists that I've favorited.

I still can't identify any pattern to the missing playlists. It doesn't depend on the number of tracks, or if there's missing tracks (removed from TIDAL's library after I added it to a playlist), or if I made it a public playlist. I'll keep testing.

**Comment by michaelherger** [comment]
But hasn't this always been the case? There's been the "My Playlists" in the main menu with the personal lists. But in the Favourites?

Maybe we should rename that menu to "My Collection", too.

**Comment by michaelherger** [comment]
I decided to make the menu "flat", no "My Collection".

**Comment by gregbreit** [comment]
Thanks. As I said in my initial post, I couldn't remember if the old plugin handled favorited playlists differently than my own. 

Still curious that a few of the "created by me" playlists show up in the favorites list, but it's likely that was the case previously and I didn't notice.

Agreed with your decision about "My Collection" -- that's TIDAL-specific nomenclature that will just cause confusion.
