### ISSUE TITLE
Track times incorrect

### ISSUE THREAD

**Issue by mpetrossian** [michaelherger/lms-plugin-tidal#11]
Thank you so much for your work on resurrecting Tidal for LMS!  This new app is notably faster than the MySB one too.

When I queue an album all the track times are incorrect except for the one playing.  When the next track plays, the previous track's time changes.  The issue is consistent across multiple devices and also iPeng

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/73385764/975d0826-4c98-47af-8cd8-4cf06026f123)

**Comment by mpetrossian** [comment]
Looks like the non-playing value is 1000x greater than the playing value?

**Comment by michaelherger** [comment]
Are you running the latest code? I've fixed that a few hours ago.

**Comment by mpetrossian** [comment]
My apologies Michael - I must have just missed that fix.  Just installed the new code and all looks great.

Many thanks

**Comment by michaelherger** [comment]
No worries! Keep the reports coming - after you've verified with the latest code 😉. Thanks!
