### ISSUE TITLE
Search-->Everything returns nothing

### ISSUE THREAD

**Issue by gregbreit** [michaelherger/lms-plugin-tidal#16]
Under "Search", there is an option to search by "Everything". No matter the search term, it always returns an empty result.

I can see in Plugin.pm that this is a temporary placeholder -- no search type is passed through to TIDAL. No doubt you're planning to implement this at some point -- I'm reporting this issue so you don't inadvertently unleash it on the world in this state.

Probably a lower priority feature, IMO, since searching by Artist, Album, Track, or Playlist all appear to function perfectly. I don't recall "Everything" being an option in the old MySB plugin.

If you do eventually implement this, it might be useful for "Everything" to work like the LMS basic library search, which categorizes search results by Albums, Artists, and Tracks. Perhaps that's the plan.

**Comment by philippe44** [comment]
I was the one putting that placeholder and from memory I did it because I saw an option in the API. I only needed the by track search as I was implementing the protocol handler part. If everything is really an option, I'll see if I can add it

**Comment by michaelherger** [comment]
Fixed in 668a15c74df4953027f58480d446ae8f0a091681.

**Comment by philippe44** [comment]
In fact there is an everything search

**Comment by GioF71** [comment]
> In fact there is an everything search

yes, I saw your implementation and realized it. I didn't use it in my plugin because this search is not required by control points, so I ended up thinking it did not exist, but I was wrong.
Sorry for misleading you.
