### ISSUE TITLE
Issue / Feature Request - No Fav Icon in Album Section

### ISSUE THREAD

**Issue by TeraX** [michaelherger/lms-plugin-tidal#18]
In the Album Section currently no Favorite Icon is showing up.
Is it possible to add Albums as favorite like in the old Tidal plugin?

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/912577/dfe27fdc-38fd-4904-a775-d8b9c0913a52)

BR
Daniel

**Comment by michaelherger** [comment]
Thanks for the heads up!
