### ISSUE TITLE
Track "more" sub-menu - "On TIdal" search option [low priority]

### ISSUE THREAD

**Issue by mpetrossian** [michaelherger/lms-plugin-tidal#25]
When you click on a track and bring up the context menu, and select the "More" option, the submenu provides an option to search on a streaming service (eg "On Qobuz").  I can't remember if the old Tidal app enabled this search, but it would be nice to have an "On Tida" search enabled too.

Thank you

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/73385764/b4001345-bcc9-424c-a568-59bce699c6df)

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/73385764/6ff1f9f7-f90c-4efa-b5e5-9bb6f00f50d3)

**Comment by mpetrossian** [comment]
Thanks Michael

**Comment by kaste** [comment]
Is this this menu here?

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/8558/9abe9387-b4d8-427d-8718-863999a1e07b)

If so, it doesn't work reliable.  E.g. it might then show this:

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/8558/018a22eb-c020-4a70-8bce-771c399aaf27)

But clicking "on TIDAL" does nothing.  🤷‍♀️

**Comment by michaelherger** [comment]
Yes, that's it. Would you have a server.log snippet? Maybe you can set logging for `plugin.tidal=INFO` to get relevant log entries.

**Comment by kaste** [comment]
If I click I get only two items in the log

```
[24-02-29 23:32:14.2787] Plugins::TIDAL::API::Async::__ANON__ (408) Using cache key 'tidal_resp:/search:countryCodeDE:limit100:queryAutechre Oversteps O=0'
[24-02-29 23:32:14.2807] Plugins::TIDAL::API::Async::__ANON__ (425) Getting /search?countryCode=DE&limit=100&query=Autechre+Oversteps+O%3D0
```
 
If I click again I get 

```
[24-02-29 23:32:41.0222] Plugins::TIDAL::API::Async::__ANON__ (408) Using cache key 'tidal_resp:/search:countryCodeDE:limit100:queryAutechre Oversteps O=0'
[24-02-29 23:32:41.0224] Plugins::TIDAL::API::Async::__ANON__ (419) Returning cached data for /search?countryCode=DE&limit=100&query=Autechre+Oversteps+O%3D0
```

**Comment by michaelherger** [comment]
`Autechre Oversteps O=0` would indeed not find anything on TIDAL when searching on listen.tidal.com. Is it available at all?

**Comment by kaste** [comment]
Ah, that's interesting and a simple finding.  I had this for different albums actually.  In my original post you can see I'm hearing something from "Kurt Rosenwinkel".  But here, none of the tracks from "Autechre - Oversteps" show any results.  Ok, I didn't try all of them just a few.

**Comment by kaste** [comment]
Actually I would have thought that this feature would let me browse to (imagine I'm in a playlist) browse to the artist, album feature the track etc.  Maybe even search the track and find alt. versions/remixes.
