### ISSUE TITLE
TIDAL Plugin settings link not visible in Default UI

### ISSUE THREAD

**Issue by mpetrossian** [michaelherger/lms-plugin-tidal#27]
The settings link isn't present in the old "default" UI settings page (but still accessible from the Advanced menu).  May be confusing to the 3 people not yet using Material skin :-)

So good to see this released so quickly!

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/73385764/a1d9cfff-7db2-4e1e-a7a2-1668ec481a40)

**Comment by michaelherger** [comment]
Fixed in e4a2d42cfc47c0f8325c0fabb331ead065ddc585.
