### ISSUE TITLE
Server error when running TIDAL plugin and LMS with --nomysqueezebox

### ISSUE THREAD

**Issue by gregbreit** [michaelherger/lms-plugin-tidal#29]
I get an error message (see below) in the LMS server.log when running LMS with the --nomysqueezebox command line option. It does not appear if the TIDAL plugin is not installed OR if I run LMS without the --nomysqueezebox option.

Looks like this is caused by Line 10 of ProtocolHandler.pm:
`use Slim::Networking::SqueezeNetwork;`

Probably left over from the old MySB version of the plugin. I doubt you're calling anything from that module anymore. Not urgent -- just something to clean up eventually.

Running LMS v8.4.0 on RPi 4B, installed via piCorePlayer.

---------------------------

[24-02-16 15:13:30.4236] main::init (386) Starting Logitech Media Server (v8.4.0, 1707213032, Thu 08 Feb 2024 12:26:00 PM CET) perl 5.032001 - arm-linux-gnueabihf-thread-multi-64int
[24-02-16 15:13:36.8783] base::import (20) Error: Support for mysqueezebox.com has been disabled. Please update your code: don't call me if main::NOMYSB.
[24-02-16 15:13:36.8787] base::import (20) Backtrace:

   frame 0: Slim::Utils::Log::logBacktrace (/usr/local/slimserver/Slim/Networking/SqueezeNetwork/Base.pm line 20)
   frame 1: (eval) (/usr/local/lib/perl5/5.32.1/base.pm line 137)
   frame 2: (eval) (/usr/local/lib/perl5/5.32.1/base.pm line 105)
   frame 3: base::import (/usr/local/slimserver/Slim/Networking/SqueezeNetwork.pm line 11)
   frame 4: Slim::Networking::SqueezeNetwork::BEGIN (/usr/local/slimserver/Slim/Networking/SqueezeNetwork/Base.pm line 0)
   frame 5: (eval) (/usr/local/slimserver/Slim/Networking/SqueezeNetwork/Base.pm line 0)
   frame 6: (eval) (/usr/local/slimserver/Cache/InstalledPlugins/Plugins/TIDAL/ProtocolHandler.pm line 10)
   frame 7: Plugins::TIDAL::ProtocolHandler::BEGIN (/usr/local/slimserver/Slim/Networking/SqueezeNetwork/Base.pm line 0)
   frame 8: (eval) (/usr/local/slimserver/Slim/Networking/SqueezeNetwork/Base.pm line 0)
   frame 9: (eval) (/usr/local/slimserver/Cache/InstalledPlugins/Plugins/TIDAL/Plugin.pm line 14)
   frame 10: Plugins::TIDAL::Plugin::BEGIN (/usr/local/slimserver/Slim/Networking/SqueezeNetwork/Base.pm line 0)
   frame 11: (eval) (/usr/local/slimserver/Slim/Networking/SqueezeNetwork/Base.pm line 0)
   frame 12: (eval) ((eval 976) line 1)
   frame 13: Slim::bootstrap::BEGIN (/usr/local/slimserver/Slim/Networking/SqueezeNetwork/Base.pm line 0)
   frame 14: (eval) (/usr/local/slimserver/Slim/Networking/SqueezeNetwork/Base.pm line 0)
   frame 15: (eval) (/usr/local/slimserver/Slim/bootstrap.pm line 287)
   frame 16: Slim::bootstrap::tryModuleLoad (/usr/local/slimserver/Slim/Utils/PluginManager.pm line 321)
   frame 17: Slim::Utils::PluginManager::load (/usr/local/slimserver/slimserver.pl line 597)
   frame 18: main::init (/usr/local/slimserver/slimserver.pl line 675)
   frame 19: main::main (/usr/local/slimserver/slimserver.pl line 1223)

**Comment by gregbreit** [comment]
Followup:

I commented out the offending line in ProtocolHandler.pm on my local installation and restarted LMS.

No server error, and no apparent impact on TIDAL functionality.

**Comment by philippe44** [comment]
Removed it in 0.6.1

**Comment by michaelherger** [comment]
Fixed in cf557656921dae589035b22c71d026491b4c45e4
