### ISSUE TITLE
Problem with meta-data when adding Tidal albums to LMS favorites

### ISSUE THREAD

**Issue by mpetrossian** [michaelherger/lms-plugin-tidal#31]
When adding an album from Tidal to LMS favorites, the meta-data isn't displayed when you subsequently select the album from favorites, but some kind of Tidal identifier (eg tidal://233808319.flc).  Adding single tracks and artists is fine. 

Running v0.6.1

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/73385764/cfecd0e6-0753-460d-9b94-ac5ef2e64629)

**Comment by TeraX** [comment]
I can confirm with LMS 8.4.0 and Tidal 0.6.1 and "old" GUI

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/912577/cc63b3e7-ee31-4833-9216-fc441ba95ebe)

**Comment by TeraX** [comment]
The same issue also happen, if a "My Mix" selection will be added to the favorites.

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/912577/b59b506c-7694-4a39-b735-760d54caf4bd)

**Comment by philippe44** [comment]
I've changed something in 0.6.2, let's see if it works and if @mherger agrees because this is a features that I added in LMS a while ago.

**Comment by mpetrossian** [comment]
Thanks Philippe - looks like it's fixed the bug.  Appreciate it

**Comment by michaelherger** [comment]
Hold on... while I'd agree that this allows you to drill down to favorites, would those favorites still play? As I understand it the current implementation would return the full menus. But in order to play back those URLs these should be a list of track URLs, not a menu?

**Comment by TeraX** [comment]
LMS GUI:
If I select a Title from the Album favourite, it open a new view, showing the Album cover and below the tidal shortlink.

If I use in the album favourite view the play button from one title, only this title will be added to the playlist and after the song finishes, they player stop.
![Screenshot_2024-02-17-19-00-58-005_com brave browser](https://github.com/michaelherger/lms-plugin-tidal/assets/912577/c9cc56dc-0427-4bb4-9e39-4ee33b467f7f)



Android App Squeezer:
If I select one song from the favourites album the full album will be added to the playlist and the selected song starts to play.
All songs in the list after that song starts also after the current played song finishes.

**Comment by philippe44** [comment]
> Hold on... while I'd agree that this allows you to drill down to favorites, would those favorites still play? As I understand it the current implementation would return the full menus. But in order to play back those URLs these should be a list of track URLs, not a menu?
>
A while ago and I think before 8.2 or 8.3 that was the case, then we changed it so that you can return just an array of tracks or a full menu. I'll look back at the PR

**Comment by michaelherger** [comment]
I think this issue can be closed?
