### ISSUE TITLE
Hi-Res: use of FLAC/MQA

### ISSUE THREAD

**Issue by manuelmaniero** [michaelherger/lms-plugin-tidal#35]
If I choose a song that is 24bit 192kHz FLAC in TIDAL app and play it via TIDAL plugin with HIRES quality, the streamed version is the MQA one. 
Example with “Dogs (2018 Remix)” by Pink Floyd.
![IMG_6480](https://github.com/michaelherger/lms-plugin-tidal/assets/28586761/692a6068-8b0b-43fd-a8b3-473d1f476596)
![IMG_6481](https://github.com/michaelherger/lms-plugin-tidal/assets/28586761/39f1a4ef-23e0-4664-8ac9-9af5c1895467)
On the LMS interface it says 24b 48kHz
![IMG_6484](https://github.com/michaelherger/lms-plugin-tidal/assets/28586761/19e328da-e6ed-4ad6-a795-e4afb63b57f1)

If I try the same thing with a 24bit 48kHz track, I get also MQA logo but the resolution is correct 
![IMG_6482](https://github.com/michaelherger/lms-plugin-tidal/assets/28586761/b55577f3-9bd9-438a-9860-a21edeb79803)
![IMG_6483](https://github.com/michaelherger/lms-plugin-tidal/assets/28586761/74ed2719-5656-49d9-a6df-46e33cf8efb0)
![IMG_6485](https://github.com/michaelherger/lms-plugin-tidal/assets/28586761/0d30bc38-219e-408d-b605-eedecdb7e15a)

**Comment by michaelherger** [comment]
The DASH based hires isn't supported at this stage.

**Comment by michaelherger** [comment]
Can we close this? Does something need to be addressed?

**Comment by manuelmaniero** [comment]
@michaelherger i am going to close this. There's another enhancement (#49) for Hi-Res.
Thanks.
