### ISSUE TITLE
8.4 only?

### ISSUE THREAD

**Issue by philippe44** [michaelherger/lms-plugin-tidal#44]
Shouldn't we have here https://github.com/michaelherger/lms-plugin-tidal/blob/3c22b806db57ab6439056ca4a8556ec840a03859/Importer.pm#L38
```
if ($class->can('ignorePlaylists') && !$class->ignorePlaylists) {
```

**Comment by michaelherger** [comment]
True... the plugin used to be 8.4 only, where we have the above. We should go back to 8.4 only 😁.
