### ISSUE TITLE
Search results incomplete

### ISSUE THREAD

**Issue by bombadil79** [michaelherger/lms-plugin-tidal#45]
I experienced the following:
Some search requests (in my case through OrangeSqueeze or the LMS-Webpage :9000) yield no or incomplete results. For example the German Audiobooks by "Die drei ???". There is only one LP shown. Searching in Tidal Android App yields over 200 LPs as expected.

**Comment by bombadil79** [comment]
Could this be an aspect of location / country living in?

**Comment by michaelherger** [comment]
I'm getting a long list of them. Living in CH. How exactly are you searching: what menu?

**Comment by TeraX** [comment]
I tried it  and I was able to found 100 albums on the Standard LMS GUI.
I used the Search function in Own Apps --> Tidal --> Search --> Album

In the Android App Squeezer I also see the same results.

**Comment by bombadil79** [comment]
I have to be precise. "die drei ???" is the input, has to be handled as Interpret, then Albums.
There are 200 plus albums of the series "Die drei Fragezeichen" (German audiobooks) in Tidal. But not shown with this search.

**Comment by TeraX** [comment]
I tried the same way you described and get a result of 42 albums of the Interpret "Die drei ???".
I checked it via listen.tidal.com and get the same 42 Albums as result.

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/912577/ef8290db-1ac6-4688-8e26-d6a9fe49de69)

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/912577/37d0fdf3-aed9-471f-a2a7-c59fe8c9fe28)

**Comment by michaelherger** [comment]
I think the problem is that "die drei ???" are not considered the artists on Tidal. So you'd have to search by album rather than artist. Metadata with streaming services often is a mess, and they obviously don't handle it the same. I'll ask my kids how they handled it (using Spotty) over lunch.

**Comment by bombadil79** [comment]
After some conversation with @michaelherger via email it may be a wrong country code somewhere in Tidal. I'm living in Germany and the Tidal support confirmed that my account was registered in Germany. In the Tidal plugins info-log appears the wrong country code (US) and I don't know where it comes from. According to the customer support the country code is set once during the registration process and cannot be changed.
Any ideas?

**Comment by michaelherger** [comment]
Here's something you could try out: go to Settings/Information to find the folder where your prefs are stored. Shut down LMS. Edit plugin/tidal.prefs to replace the account's `countryCode` value with your country. If there's none for your account, add a line (with four leading spaces, to align with `created` and `city` or whatever). Then restart LMS and give it another try.

**Comment by bombadil79** [comment]
After updating to 0.9.1 it works fine.
Thank you for the great support, Michael!
