### ISSUE TITLE
Link for tidal auth not available in Daphile

### ISSUE THREAD

**Issue by NiX0N555** [michaelherger/lms-plugin-tidal#46]
Hello!

Could you help me, please, I have a problem with displaying the Tidal authorization link in Daphile. ( [https://www.daphile.com/](url) ) The auth link in plugin is not displayed. I wrote to the Daphile developers several times, but they do not respond. Is it possible to solve this problem? Thanks!

![1](https://github.com/michaelherger/lms-plugin-tidal/assets/162463874/c41b5836-26a1-4a4b-b461-71c1f1765e36)
![2](https://github.com/michaelherger/lms-plugin-tidal/assets/162463874/cc341a3e-ca90-4ca3-89ca-6106b7648a77)
![3](https://github.com/michaelherger/lms-plugin-tidal/assets/162463874/2265f14e-2e76-4fa5-bc22-b5c2519882d8)

**Comment by michaelherger** [comment]
Can you access LMS directly using the Default skin? http://192.168.1.128:9000

**Comment by NiX0N555** [comment]
> Can you access LMS directly using the Default skin? http://192.168.1.128:9000

Yes. But it's the same here. 
![4](https://github.com/michaelherger/lms-plugin-tidal/assets/162463874/cbc8574a-5fc5-4740-ad61-e202ab600662)

**Comment by michaelherger** [comment]
Please enable debug logging for `plugin.tidal` (Settings/Information), try again, then send me your server.log.zip from that page (https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a).

**Comment by NiX0N555** [comment]
> Please enable debug logging for `plugin.tidal` (Settings/Information), try again, then send me your server.log.zip from that page (https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a).

OK.
[server.log.zip](https://github.com/michaelherger/lms-plugin-tidal/files/14513932/server.log.zip)

**Comment by michaelherger** [comment]
Thanks! Unfortunately there's not much in there except a "403 Forbidden". You're not behind a filtering proxy, are you?

Could you please enable logging for `network.asynchttp`, try again, upload again? This will be super noisy. So please make sure you disable it again after the test.

**Comment by NiX0N555** [comment]
> Thanks! Unfortunately there's not much in there except a "403 Forbidden". You're not behind a filtering proxy, are you?
> 
> Could you please enable logging for `network.asynchttp`, try again, upload again? This will be super noisy. So please make sure you disable it again after the test.

I did it. Send to Dropbox.

**Comment by NiX0N555** [comment]
And no proxy.

https://account.tidal.com/login

![5](https://github.com/michaelherger/lms-plugin-tidal/assets/162463874/762da202-684c-44bf-a111-0a9936eb45d9)

**Comment by NiX0N555** [comment]
Michael, It seems that I understand what the problem is... The resource "https://auth.tidal.com/v1/oauth2/device_authorization" that is used in your plugin is blocked in my country ((((( Right?

**Comment by michaelherger** [comment]
While I didn't see that message I saw that CloudFront rejected with a 403. And I was wondering about your country, too. Is TIDAL not officially available where you live?

**Comment by alexjulien** [comment]
Maybe I'm talking nonsense, but it _might_ work if you try to auth through a VPN, and things will operate normally later, without VPN, as long as the AUTH token remains valid.

**Comment by NiX0N555** [comment]
> Maybe I'm talking nonsense, but it _might_ work if you try to auth through a VPN, and things will operate normally later, without VPN, as long as the AUTH token remains valid.

No, you are not talking nonsense. I also think that through a VPN everything will be fine. But this is very inconvenient, the speed will immediately become low. I'll check it one of these days... Michael, thank you very much for your feedback and support!!! It was very nice to chat! I think the issue can be closed.

**Comment by michaelherger** [comment]
Can you confirm which country you're living in? I don't know whether this is the official list of countries where TIDAL is available. But can you confirm you're in one of them?

https://recordjet.com/en/partners/tidal

**Comment by NiX0N555** [comment]
> Can you confirm which country you're living in? I don't know whether this is the official list of countries where TIDAL is available. But can you confirm you're in one of them?
> 
> https://recordjet.com/en/partners/tidal

I am from Russia. And it is not on the list ((( Hmm... Strange, then why does "https://account.tidal.com/login" open..

**Comment by weaselchops** [comment]
Same issue in the UK.

```
[24-03-15 14:44:18.3554] Plugins::TIDAL::Settings::Auth::__ANON__ (51) Did not get any account information back
[24-03-15 14:46:04.7844] Plugins::TIDAL::API::Auth::__ANON__ (212) Error: 400 Bad Request
[24-03-15 14:46:04.7856] Plugins::TIDAL::API::Auth::__ANON__ (214) do {
  my $a = bless([
    sub { "???" },
    sub { "???" },
    { cache => 0, expiry => 0, timeout => 15 },
    bless({
      ALL            => sub { "???" },
      DEBUG          => 'fix',
      ERROR          => sub { "???" },
      FATAL          => 'fix',
      INFO           => 'fix',
      OFF            => 'fix',
      TRACE          => 'fix',
      WARN           => 'fix',
      additivity     => 1,
      appender_names => [],
      category       => "network.asynchttp",
      is_ALL         => 0,
      is_DEBUG       => 0,
      is_ERROR       => 1,
      is_FATAL       => 1,
      is_INFO        => 0,
      is_OFF         => 1,
      is_TRACE       => 0,
      is_WARN        => 0,
      layout         => undef,
      level          => 40_000,
      num_appenders  => 0,
    }, "Slim::Utils::Log"),
    "POST",
    "https://auth.tidal.com/v1/oauth2/device_authorization",
    "400 Bad Request",
    undef,
    undef,
    undef,
    undef,
    undef,
    undef,
  ], "Slim::Networking::SimpleAsyncHTTP");
  $a->[3]{DEBUG} = $a->[3]{ALL};
  $a->[3]{FATAL} = $a->[3]{ERROR};
  $a->[3]{INFO} = $a->[3]{ALL};
  $a->[3]{OFF} = $a->[3]{ERROR};
  $a->[3]{TRACE} = $a->[3]{ALL};
  $a->[3]{WARN} = $a->[3]{ALL};
  $a;
}
[24-03-15 14:46:04.7859] Plugins::TIDAL::Settings::Auth::__ANON__ (51) Did not get any account information back
```
