### ISSUE TITLE
selecting artist does not show EP's or compilations

### ISSUE THREAD

**Issue by real-t0mg** [michaelherger/lms-plugin-tidal#48]
First, **thank you for fixing the Tidal playback past the cutover date**. Second, the plugin does not show the full available catalogue for a selected artist, it only lists the regular albums, no EP's nor compilations. It's an issue but I'm not sure if this is a bug. 

To reproduce, select or search for an artist, only selection available is "albums", "top tracks" and "artist mix", no EP's nor compilations.

![Screenshot_2024-03-07_14-59-25](https://github.com/michaelherger/lms-plugin-tidal/assets/13096976/e8f3f07b-2f32-4b7a-b69f-4a5cc533865e)
![Screenshot_2024-03-07_14-59-10](https://github.com/michaelherger/lms-plugin-tidal/assets/13096976/13573d4f-7df8-47f7-9c54-50141eb3a504)

**Comment by michaelherger** [comment]
Thanks for the hint. We'll have to look into this. The currently released code really had to be created quickly, as you'll understand. We know that some features are still missing.
