### ISSUE TITLE
More menu is missing some functionality

### ISSUE THREAD

**Issue by alexjulien** [michaelherger/lms-plugin-tidal#50]
If I open the MORE menu of a TIDAL track in the queue, I can't
- Go to the Artist
- Go to the Album
- Go to Track Radio

And if the track is not on the queue but in the Library panel, I only get the tidal:// url.

Could you eventually implement these options, and consistently across both panels?

**Comment by michaelherger** [comment]
Wouldn't you get the "On TIDAL" link from where you can browse to radio etc.?

**Comment by haldi4803** [comment]
is it just me or is the "on TIDAL" button broken? It only works by half of the tracks in the Playlist.
(Edit: Or it works by all of them already played, but queued tracks only work maybe?)


Also Track Radio is something thats not available in that menu.
![image](https://github.com/michaelherger/lms-plugin-tidal/assets/17104473/e74cf3a0-ac68-4dd7-80f1-c1c566aee1bc)

**Comment by alexjulien** [comment]
> Wouldn't you get the "On TIDAL" link from where you can browse to radio etc.?

Not really
From Browse > Tidal:
![Screenshot_20240308-111940](https://github.com/michaelherger/lms-plugin-tidal/assets/17480397/06d35127-40f8-49e5-bf31-3dc46b9a4a66)
You only get the Tidal url
![Screenshot_20240308-112011](https://github.com/michaelherger/lms-plugin-tidal/assets/17480397/d712c55f-4d25-4382-abd8-182ec113232a)

From the queue
![Screenshot_20240308-112034](https://github.com/michaelherger/lms-plugin-tidal/assets/17480397/dbbe2f99-4966-444c-a642-30118e2df824)
You get these options 
![Screenshot_20240308-112042](https://github.com/michaelherger/lms-plugin-tidal/assets/17480397/d19e993d-7059-4982-8caf-3ba42c05337d)
The On Tidal option gives you Tidal search 
![Screenshot_20240308-112052](https://github.com/michaelherger/lms-plugin-tidal/assets/17480397/88601487-fd61-4d68-8d20-07c145c09530)
Search results
![Screenshot_20240308-112132](https://github.com/michaelherger/lms-plugin-tidal/assets/17480397/b2b7efbe-90ae-4d19-b3d1-93669d1108b7)
And back to URL
![Screenshot_20240308-112138](https://github.com/michaelherger/lms-plugin-tidal/assets/17480397/df7baa27-a713-44ac-9e30-b0bc56af9b65)
![Screenshot_20240308-112420](https://github.com/michaelherger/lms-plugin-tidal/assets/17480397/0aa62705-5f5b-4bff-b42e-1cea4910ae0e)
![Screenshot_20240308-112426](https://github.com/michaelherger/lms-plugin-tidal/assets/17480397/a3fa289a-c75e-4f06-ba8c-89f4dc514036)

**Comment by michaelherger** [comment]
Relevant discussion: the More menu is not always the same...

https://forums.slimdevices.com/forum/developer-forums/developers/1684336-trackinfo-for-plugins

**Comment by philippe44** [comment]
Done in 1.1

**Comment by michaelherger** [comment]
Thanks @philippe44
