### ISSUE TITLE
Local Tidal (0.9) is not working in Daphile.

### ISSUE THREAD

**Issue by Boendigo** [michaelherger/lms-plugin-tidal#51]
LMS in Daphile is 8.3.1

**Comment by michaelherger** [comment]
Daphile needs an update. There will be way bigger problems in a week when mysqueezebox.com will be shut down.

**Comment by rrajnoha** [comment]
Yes, the plugin really doesn't work in Daphile.
I compared version 0.9.0 with version 0.8.0 and it is in the install.xml file
<targetApplication>
     <minVersion>8.4.0</minVersion>
     <maxVersion>*</maxVersion>
   </targetApplication>
I tried overwriting to <minVersion>8.3.0</minVersion> and the plugin started running after a reboot. I had to re-register in the plugin settings.

I have no idea why the author changed the LMS compatibility to 8.4? It is possible that in some states the plugin will not work, but it works for now.

**Comment by philippe44** [comment]
AFAIK online library integration does not work and crashes, stopping the whole scanning process with < 8.4

**Comment by michaelherger** [comment]
I plan to release 8.5 next week. Please get in touch with the Daphile maintainer to ask him to update ASAP.

**Comment by michaelherger** [comment]
Please inform the Daphile developer on https://www.daphile.com/#contact

**Comment by abolsisgood** [comment]
Mail response is automated. It seems that Daphile is being abandoned for good, and what a shame... It was a neat little package with excelent sound and easy handling. 
Last update is from jan. 23.
Amen.
