### ISSUE TITLE
[Feature Request] Like Tune on Tidal

### ISSUE THREAD

**Issue by haldi4803** [michaelherger/lms-plugin-tidal#53]
Hello,
LMS has the feature to "favorite" a Tune. This adds the Tidal link to the home screen favorites.
Whenever I listen to a mixed playlist on Tidal I find a cool tune I have to open the tidal app, search tune by name and like it to hear more similar stuff.
Would it be possible to use the API to like tunes?
Does that sound like a feature worth implementing?

**Comment by michaelherger** [comment]
Definitely on my to do list.

**Comment by philippe44** [comment]
Starting with 1.1,x, if you click on "more", you can add it to a Tidal private playlist or to Tidal favorites
