### ISSUE TITLE
"My Mix" returns empty list from Tidal Family "main account"

### ISSUE THREAD

**Issue by renebk** [michaelherger/lms-plugin-tidal#54]
I have a setup with a Tidal family subscription, one main account and two family members. The two family member accounts retrieves the "My Mix" flawlessly. However, on the main account, nothing is returned. The main account is "managed" by my mobile operator and uses MSISDN as login. Here are log details, when trying to retrieve "My Mix" on main account, and later on a family member:

[24-03-15 06:25:20.3424] Plugins::TIDAL::API::Async::__ANON__ (412) Using cache key 'tidal_resp:/mixes/daily/track:185215176:countryCodeDK:limit2000'
[24-03-15 06:25:20.3427] Plugins::TIDAL::API::Async::__ANON__ (424) Returning cached data for /mixes/daily/track?countryCode=DK&limit=100
[24-03-15 06:25:20.3428] Plugins::TIDAL::API::Async::__ANON__ (425) []
[24-03-15 06:25:30.4619] Plugins::TIDAL::API::Async::__ANON__ (412) Using cache key 'tidal_resp:/mixes/daily/track:174823264:countryCodeDK:limit2000'
[24-03-15 06:25:30.4625] Plugins::TIDAL::API::Async::__ANON__ (424) Returning cached data for /mixes/daily/track?countryCode=DK&limit=100
[24-03-15 06:25:30.4682] Plugins::TIDAL::API::Async::__ANON__ (425) [
  {
    artists => [
          { id => 7
            ..
(full list is retrieved)

Tried downgrading the plugin to earlier version 8.1, it gave same result. Also tried deleting LMS cache. Server details:

Version: 8.5.0 - 1710422688 @ Thu 14 Mar 2024 03:09:10 PM CET
Værtsnavn: raspberrypi
Serverens IP-adresse: 10.0.0.35
Styresystem: Debian - DA - utf8
Platformarkitektur: armv7l-linux
Perl-version: 5.36.0 - arm-linux-gnueabihf-thread-multi-64int
Audio::Scan: 1.08
IO::Socket::SSL: 2.081
Databaseversion: DBD::SQLite 1.58 (sqlite 3.22.0)

**Comment by michaelherger** [comment]
Would other personal content return successfully? And would you have those mixes in TIDAL's app? 

As I don't see the full log file I must assume the request didn't return with an error, but empty indeed. In that case there's not much we can do: when the API doesn't return any data (and no error either), then we must assume there's nothing to return.

You could
* shut down LMS
* delete `cache.db`
* restart LMS
* enable debug logging for `plugin.tidal`
* open that menu again
* send me the full server.log.zip (https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a)

**Comment by michaelherger** [comment]
One more thing: try the same using the URL as you can find it in TIDAL. Go to your mix, click the three dots, Share, copy the mix URL (something like https://tidal.com/browse/mix/abc123def456) and add that URL to the play queue.

**Comment by renebk** [comment]
All other personal content is returned correctly (artists, playlists, tracks). Tried copying an URL from one of the mixes from Tidal to LMS play queue and it adds and plays. However, the URL strong seems quite a bit longer than the format you spec'ed:
https://tidal.com/mix/00268901750d55213056f95bf90647

**Comment by renebk** [comment]
Whoops, can see I was in wrong listing. My mixes is indeed empty on Tidal, so works as expected. Sorry closing issue
