### ISSUE TITLE
Replay Gain for tidal 

### ISSUE THREAD

**Issue by Esad-np** [michaelherger/lms-plugin-tidal#55]
Great work on the tidal plugin so far guys! Please share/provide the donation link ...

Issue: playing tidal songs via LMS is very loud and I think this is because the ReplayGain is not retrieved from tidal. 
I checked few songs from Tidal and same songs from Qobuz and loudness difference is incredible. As far as I can tell this is only because Qobuz plugin handles correctly the ReplaiGain (Track and Album) ...

**Comment by Esad-np** [comment]
here is the example same song from Qobuz and tidal:
[24-03-17 15:22:56.7167] Plugins::Qobuz::ProtocolHandler::trackGain (185) {
  artist           => {
                        albums_count => 18,
                        id => 520_907,
                        image => undef,
                        name => "Psychic Ills",
                        picture => undef,
                        slug => "psychic-ills",
                      },
  duration         => 2454,
  genre            => "Alternative & Indie",
  genres_list      => [
                        "Pop/Rock",
                        "Pop/Rock\x{2192}Rock",
                        "Pop/Rock\x{2192}Rock\x{2192}Alternatif et Ind\xE9",
                      ],
  goodies          => [],
  id               => "0616892178866",
  image            => "https://static.qobuz.com/images/covers/66/88/0616892178866_600.jpg",
  isClassique      => 0,
  label            => "Sacred Bones Records",
  labelId          => 100_056,
  media_count      => 1,
  parental_warning => bless(do{\(my $o = 0)}, "JSON::XS::Boolean"),
  release_type     => "album",
  replay_gain      => "-11.43",
  replay_peak      => 1,
  title            => "Hazed Dream",
  year             => 2011,
}
[24-03-17 15:22:56.7168] Plugins::Qobuz::ProtocolHandler::trackGain (188) Using album gain value of -11.43 : 1 for track: Mind Daze
[24-03-17 15:22:56.7169] Plugins::Qobuz::ProtocolHandler::trackGain (192) Net replay gain: -11.43
[24-03-17 15:23:03.5913] Plugins::TIDAL::API::Async::__ANON__ (430) Getting /tracks/19329987/playbackinfopostpaywall?assetpresentation=FULL&audioquality=HI_RES&countryCode=GB&limit=100&playbackmode=STREAM
[24-03-17 15:23:03.5921] Plugins::TIDAL::ProtocolHandler::getNextTrack (197) Getting next track playback info for tidal://19329987.flc
[24-03-17 15:23:03.7781] Plugins::TIDAL::API::Async::__ANON__ (439) {
  albumPeakAmplitude => 1,
  albumReplayGain    => "-11.43",
  assetPresentation  => "FULL",
  audioMode          => "STEREO",
  audioQuality       => "LOSSLESS",
  bitDepth           => 16,
  manifestMimeType   => "application/vnd.tidal.bts",
  sampleRate         => 44_100,
  trackId            => 19_329_987,
  trackPeakAmplitude => 1,
  trackReplayGain    => "-11.43",
}

When I play them, the web interface only shows the ReplayGain for Qobuz track but no ReplayGain is shown for Tidal track

**Comment by michaelherger** [comment]
This should have been addressed in v1.0. Can you please confirm?

**Comment by Esad-np** [comment]
All fine now ! Thank you !!!
