### ISSUE TITLE
"On Tidal" query returns empty string

### ISSUE THREAD

**Issue by renebk** [michaelherger/lms-plugin-tidal#56]
I have a playlist containing entries from Tidal. If I select "more" and then "On TIDAL", no data appears. If I take a look in the debug log, I can see the query is made towards Tidal and empty string is returned, example: 
[24-03-18 05:56:47.3271] Plugins::TIDAL::API::Async::__ANON__ (412) Using cache key 'tidal_resp:/search:countryCodeDK:limit100:queryNick Cave CARNAGE White Elephant'
[24-03-18 05:56:47.3274] Plugins::TIDAL::API::Async::__ANON__ (424) Returning cached data for /search?countryCode=DK&limit=100&query=Nick+Cave+CARNAGE+White+Elephant
[24-03-18 05:56:47.3280] Plugins::TIDAL::API::Async::__ANON__ (425) {
  albums    => { items => [], limit => 100, offset => 0, totalNumberOfItems => 0 },
  artists   => { items => [], limit => 100, offset => 0, totalNumberOfItems => 0 },
  playlists => { items => [], limit => 100, offset => 0, totalNumberOfItems => 0 },
  topHit    => undef,
  tracks    => { items => [], limit => 100, offset => 0, totalNumberOfItems => 0 },
  videos    => { items => [], limit => 100, offset => 0, totalNumberOfItems => 0 },
}

Appears to be a limitation in the Tidal Search function. If I place the same query in the Tidal APP, I also get no results.
Seems like the search string Artist+Album+Track is "too advanced" for Tidal. Artist+Album and Artist+Track returns results. However, Album+Track doesn't. Maybe the API has changed behavior?

For Tidal specific tracks, the "Get Single track" API call would be obvious. However this would only work for Tidal tracks.

**Comment by michaelherger** [comment]
I have plans to be smarter (not only for TIDAL, but all tracks coming from external sources), to not rely on text search when there's an external ID available. Alas, if there's an issue with the text search as you outline, then I'll have to look into this anyway. Thanks for the heads up!

**Comment by kaste** [comment]
That has been resolved by #57
