### ISSUE TITLE
Wrong song length, before playback

### ISSUE THREAD

**Issue by GioF71** [michaelherger/lms-plugin-tidal#6]
Hello, it appears that when one adds a song to the playlist, its displayed duration is wrong.
Take for example "Wanna be starting something" from Thriller album by M. Jackson.
Enqueue the track, look at the playlist: it shows "100:50:00" as the duration.
When playback starts, the information goes back to the actual 6:02 duration.
See the screenshot:

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/5603160/497f8ca0-84d3-4f93-8f8c-9cec5eb3a589)

Of course, congratulations for the great work

**Comment by GioF71** [comment]
> That's along song! Thanks for this very first bug report on this fresh project!
> 

So there was a trophy or something for the first bug report? :-)

**Comment by philippe44** [comment]
Duration in this api is in sec and I thought it was ms...

**Comment by kronzo** [comment]
@philippe44 : well done, now it's OK. Thanks

**Comment by TeraX** [comment]
![2024-02-12 20_14_27-Logitech Media Server](https://github.com/michaelherger/lms-plugin-tidal/assets/912577/560b53e6-520e-46a9-bf81-e7cddbf8ab9b)

Looks good!

**Comment by michaelherger** [comment]
Fixed in cafca3926603b428086fee91f23ef440067c7ac8. Thanks!
