### ISSUE TITLE
Default action is not "play" anymore

### ISSUE THREAD

**Issue by kaste** [michaelherger/lms-plugin-tidal#68]
I'm comparing 7a5ac77 with current main at 64acec0.  (T.i. after the big changes introduced by @philippe44)

On current main, clicking on an item (song) does NOT start the playback at that song, loading the complete album into the queue.  

https://github.com/michaelherger/lms-plugin-tidal/assets/8558/aacef12b-f488-455f-86de-5e3574dd8d11

The video shows SqueezePlay but the Squeezebox Touch behaves the same.  And also the Material Skin browser on my phone behaves similar in that it only opens the context/long press menu.  

On 7a5ac77 (t.i. my last PR checked in), it looks like this:

https://github.com/michaelherger/lms-plugin-tidal/assets/8558/9239b4cf-6a6e-4a1b-af32-934fc4de2337

**Comment by philippe44** [comment]
Yo have to long press it

**Comment by kaste** [comment]
The long press opens the menu as always, but the short tap does nothing.  Before the change a short tap enqueued the whole album and started playback at the song I tapped.

**Comment by kaste** [comment]
Oh, that's a bummer.  My (retarded) child can't use the menu.  

Can we at least re-arrange the items in the menu so that "play" is the first item?

**Comment by philippe44** [comment]
I might have found a solution with Jive-specific code

**Comment by philippe44** [comment]
If you edit Plugin.pm::renderTrack and add, after the "itemAction"
```
jive => {
			nextWindow => 'nowPlaying',
			actions => {
				go => {
					player => 0,
					cmd    => [ 'tidal_browse', 'playlist', 'play' ],
					params => { id => $item->{id} },
				}
			},
		},
```
Does it do what you want?

**Comment by kaste** [comment]
I have this diff now

```diff
diff --git a/Plugin.pm b/Plugin.pm
index b2cf7f3..f640df9 100644
--- a/Plugin.pm
+++ b/Plugin.pm
@@ -915,6 +915,16 @@ sub _renderTrack {
 				},
 			},
 		},
+		jive => {
+			nextWindow => 'nowPlaying',
+			actions => {
+				go => {
+					player => 0,
+					cmd    => [ 'tidal_browse', 'playlist', 'play' ],
+					params => { id => $item->{id} },
+				}
+			},
+		},
 	};
 }
 ```

but that does nothing on tap.  It breaks the long tap with the following LOG:

```log
[24-04-01 11:41:18.6905] Slim::Control::Request::execute (1880) Error: While trying to run function coderef [Plugins::TIDAL::InfoMenu::menuInfoWeb]: [Can't use an undefined value as a subroutine reference at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/TIDAL/InfoMenu.pm line 147.
]
```

**Comment by philippe44** [comment]
Oh, I did not check that, but did you also use my most recent PR. It requires the full extended browse option.

**Comment by kaste** [comment]
I tried with 04bbc94 just now with no success.  The strange UX is that when you browse "my music -> albums" it works and starts playback just by tapping on a track, but when you browse "tidal -> albums" it switches to the "now playing" view but nothing happens actually.

**Comment by philippe44** [comment]
This is weird as this is just what I tried on my squeezeplay. What is the setting of defeat touch to play ?

**Comment by philippe44** [comment]
No, you're right this is still no the correct fix. I'll look at that

**Comment by philippe44** [comment]
I hope this is the right one https://github.com/michaelherger/lms-plugin-tidal/pull/71

**Comment by michaelherger** [comment]
Fixed via https://github.com/michaelherger/lms-plugin-tidal/commit/7dd217e09327959323b243c85ced459ec32abd82.

**Comment by kaste** [comment]
You're gold here.  You both are.
