### ISSUE TITLE
Question, not an issue

### ISSUE THREAD

**Issue by philippe44** [michaelherger/lms-plugin-tidal#69]
https://github.com/michaelherger/lms-plugin-tidal/blob/7b2f370c8e9e7152de2f7c8ebca25dd8ce091a26/Importer.pm#L295

Why doing a sort here?

**Comment by michaelherger** [comment]
Good question. I think at some point I wanted to have a well defined order for testing purposes and stuck with it...

BTW: you should be able to comment on a commit directly.
