### ISSUE TITLE
[Enhancement Request] Include For Me items in web app

### ISSUE THREAD

**Issue by EricB-dev** [michaelherger/lms-plugin-tidal#72]
Can we have access to the For You items in the LMS web app?

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/60356529/15e2935d-862c-4f67-a65a-efb997bf6d66)

![image](https://github.com/michaelherger/lms-plugin-tidal/assets/60356529/73086446-299f-492b-9bf5-09f85b7b492a)

Thanks
-Eric

**Comment by philippe44** [comment]
@michaelherger : I've started to work on that on my separate branch. It's not ready yet, but just wanted to let you know

**Comment by michaelherger** [comment]
Will this require using some unofficial endpoint?

**Comment by EricB-dev** [comment]
@philippe44 Awesome thanks!

**Comment by philippe44** [comment]
> Will this require using some unofficial endpoint?
>
No, unlike the Deezer version where some requests ressemble a bit to web scraping (but are still not)
