### ISSUE TITLE
Main Menu items not updated after account switch

### ISSUE THREAD

**Issue by renebk** [michaelherger/lms-plugin-tidal#81]
Setup: Tidal family subscription with 3 accounts. 
Problem: 
When I switch Tidal account on a player, and select the main menu (menu entry with house icon), seem like
 items are not updated to the new account. Other content like, "My Mix", "Artists" is updated correctly. 
If I stop the server and deletes cache, the account is correctly switched when the server is restarted. 

How to validate:
1. Start Tidal and go to Main Menu. Validate content
2. Change Tidal account on the player
3. Go to Main Menu and validate content is not changed.

I´ve done a complete log of the problem, with a fresh server reboot, and then list Main before and after an account shift. 
[server.log](https://github.com/michaelherger/lms-plugin-tidal/files/15141447/server.log)

**Comment by philippe44** [comment]
I'll see what I can do but these are undocumented api so not easy to handle

**Comment by philippe44** [comment]
I forgot to cache "by user" so you were tapping into the same cache for everybody. I think 1.3.2 should fix this

**Comment by renebk** [comment]
Thanks Phillippe, works :-) Initial testing did not look promising. But decided to wait some hours and try again. And now everything works really nice. I've been switching randomly between the 3 accounts several times and the information is updated immediately and correctly. Guessing the initial experiences is due to cache, refresh/time-out. Cache is some sort of black magic to me.

**Comment by renebk** [comment]
Update: Played more around late last evening and this morning. Unfortunately behaviour is not consistent. It's a bit random on when switch and update on information happens. Not an expert here, but looks like cache challenges.

**Comment by michaelherger** [comment]
What version did you last try with? Also: could you please enable `info` logging (not `debug`!) for `plugin.tidal`, run your tests, then provide the resulting `server.log.zip` (see Settings/Advanced/Logging)?

**Comment by michaelherger** [comment]
One problem might be that the data had been cached for too long before the update. Now even if the update would not do this any more, the cache still returns the data, as it was cached _before_ the fix. You might have to be patient to wait for the cached entries to eventually expire, or delete cache.db from the cache folder (while LMS is shut down).

**Comment by renebk** [comment]
I´ve gotten quite familiar with the "stop" -> "delete cache" -> "start" routine. Latest this morning, removing all .db files from the cache folder "/var/lib/squeezeboxserver/cache" (any additional configurations I am missing to delete?). It did not improve, unfortunately. All three accounts get the same list of recommended radio stations. Again, problem solely relates to the "Main Menu" items - I use the "Recommended Radio Stations" as reference.  
Good point about the log, it had become quite messy. I've done a clean up of that as well and attached a fresh version.
[server.log (6).zip](https://github.com/michaelherger/lms-plugin-tidal/files/15183634/server.log.6.zip)

Probably getting to the end on this one, as no obvious reason can be found for the behavior.

**Comment by philippe44** [comment]
Done in 1.4.6

**Comment by renebk** [comment]
I added the codechange and have done more than 50 account switches across several players all successful. Works very solid and fast. Thank you and kudos Phillippe
