### ISSUE TITLE
Home -> Recently Played is always empty

### ISSUE THREAD

**Issue by Vegz78** [michaelherger/lms-plugin-tidal#83]
Home -> Recently Played is always empty:
![image](https://github.com/michaelherger/lms-plugin-tidal/assets/49032025/1a41285b-99fe-42cb-a728-6d13700bc361)

For more details, follow the discussion from this point:
https://forums.slimdevices.com/forum/user-forums/3rd-party-software/1686851-announce-tidal-local-plugin?p=1703299#post1703299

**Comment by Vegz78** [comment]
Ok, I just now uploaded the server.log with the DEBUG logging enabled for the Tidal plugin using @michaelherger's provided Dropbox link.

So, in the log you will find the following of my Tidal actions from the last restart of the server:
1. iPeng: Search for the song "Mandalorian", then going into the context menu and trying to play a songmix. Waiting for the query to time out and return an empty playlist.
2. iPeng: Return to the search result and playing the "Mandalorian" song, then emptying the playlist.
3. Squeezelite-X: Search for the song "Mandalorian", then going into the context menu and playing the songmix successfully. Emptying the playlist.
4. iPeng: Navigating to Tidal -> Home -> "Recently played". Returning empty list.
5. Squeezelite-X: 4. iPeng: Navigating to Tidal -> Home -> "Recently played". Returning empty list.

**Comment by michaelherger** [comment]
Could you please give 1.4.1 a try? That menu item seems to be using a type we haven't seen before. Should be supported in 1.4.1. That said: I haven't been able to test it, as I don't get those items.

**Comment by Vegz78** [comment]
> Could you please give 1.4.1 a try?

Wow, that was quick!

_Recently Played_ still empty in iPeng and not responding in the web player interface/Squeezelite-X, I'm afraid.

**Comment by michaelherger** [comment]
With no additional errors/messages in server.log?

**Comment by Vegz78** [comment]
> With no additional errors/messages in server.log?

Sorry, I will check pronto!

**Comment by Vegz78** [comment]
In debug and info logging I saw a long list related to recently played:
```
...
                    title          => "Recently played",
                    type           => "MIXED_TYPES_LIST",
```

And a lot of error messages which I could not connect to this in time and name.

You will soon receive a new upload of the debug log, after a restart and only trying to access recently played in the Tidal plugin.

**Comment by Vegz78** [comment]
New server.log uploaded again to your Dropbox.

**Comment by michaelherger** [comment]
Thanks for the update! There's always more... Unfortunately I don't get any of those `MIXED_TYPES_LIST` items and therefore can't test the changes myself. But it seem as if those were structured slightly different. Another update is on its way. You know the procedure 😁. Thanks for the testing!

BTW: would you be able to edit a plugin file to apply changes manually? This would avoid creating a flood of quick releases.

**Comment by Vegz78** [comment]
> Thanks for the update! 

You guys are the ones who deserve thanking! Do you get some sleep between your amazing work sessions?

> Unfortunately I don't get any of those `MIXED_TYPES_LIST` items and therefore can't test the changes myself. But it seem as if those were structured slightly different. 

Yeah, _Recently Played_ contains playlists, tracks, albums etc. in the same list...

But strange that you don not get any of those for your Tidal user! In the regular Tidal web and mobile apps, the _Recently Played" list, along with _For You_, _Custom Mixes_, _From Our Editors_, _Radio Stations For You_, _Recommended New Tracks_, _Suggested New Albums for You_, _Your Listening History_, _Popular Playlists on Tidal_, _Tidal Rising_, _Popular Albums_, _Radio Stations for Your_, _New Releases for You_, _Producers and Songwriters, and an ever changing selection of _"Beacuse you listened to..." lists, appear for me directly under the welcome Home screen, and I have not done anything special to my knowing(But I have used this subscription for a long time with many stored and favorite albums, playlists, tracks, artists etc.):
![image](https://github.com/michaelherger/lms-plugin-tidal/assets/49032025/658a3ec6-20c2-4fd6-b3b5-904d347be140)
![image](https://github.com/michaelherger/lms-plugin-tidal/assets/49032025/7bfcf694-713c-4021-af08-18c51715ce71)
etc...

>Another update is on its way. You know the procedure 😁. Thanks for the testing!

Great and thank you very much! I will download and test now and get back to you with results and (hopefully not any new) logs!

> BTW: would you be able to edit a plugin file to apply changes manually? This would avoid creating a flood of quick releases.

By this, you mean that I just copy over the updated files from the GitHub repo to the plugin folder and restart the server, or something else? I understand that you do not want a lot of draft and untested changes published as releases, and will do what I can to help, maybe requiring some minor instructions... ;-)

**Comment by Vegz78** [comment]
I have the pleasure to report that v1.4.4 works like charm for _Recently Played_!!!

I could now open and play everything I tested of albums, playlists, artists, tracks in the list!

THANK YOU!!! ;-)

**Comment by Vegz78** [comment]
Do you need another log to check and see if any non essential errors remain, or is this functionality test sufficient?

**Comment by michaelherger** [comment]
If it's working I won't bother further investigating the menu 😀.

And yes, I suggested you could just replace a file or two in your installation. But that' for next time.

**Comment by Vegz78** [comment]
Good philosophy!

Replacing a file or two in the plugins folder with some downloads from Github I should be able to manage. Until next time, then.

Thanks again!
