### ISSUE TITLE
Maax

### ISSUE THREAD

**Issue by Patergnani28** [michaelherger/lms-plugin-tidal#85]
I need tidal plugins in daphile

**Comment by philippe44** [comment]
Daphile is outdated and not maintained.please go to the forums for help, there is nothing we'll do here

**Comment by michaelherger** [comment]
As @philippe44 said this is entirely up to the Daphile developer. But there actually seems to be some activity on their side. See https://forums.slimdevices.com/forum/user-forums/general-discussion/1699297-daphile-update-lms?p=1703417#post1703417.
