### ISSUE TITLE
Hires FLAC i

### ISSUE THREAD

**Issue by JRH1003** [michaelherger/lms-plugin-tidal#88]
Thanks for the Tidal local plug-in . As Tidal is now switching all music to HiRes FLAC, it would be great to forward this to LMS. MQA used to play as HiRes, where HiRes FLAC plays as normal 16 bit CD quality. Would it be possible to add HiRes for FLAC in the Plug-in ?

Thanks.

**Comment by michaelherger** [comment]
Closing this in favor of #89. Thanks!
