### ISSUE TITLE
Can't get 'My Mix'

### ISSUE THREAD

**Issue by kronzo** [michaelherger/lms-plugin-tidal#9]
I get an empty 'My Mix'.

![Screenshot at Feb 12 22-41-27](https://github.com/michaelherger/lms-plugin-tidal/assets/6114202/e68bd997-de39-4e3f-b22d-76a646f42ef6)

_Excerpt from logfile:_

> [24-02-12 22:35:17.5955] Plugins::TIDAL::API::Async::__ANON__ (496) Using cache key 'tidal_resp:/mixes/daily/items:countryCodeDE:limit2000'
[24-02-12 22:35:17.5958] Plugins::TIDAL::API::Async::__ANON__ (513) Getting /mixes/daily/items?countryCode=DE&limit=50
[24-02-12 22:35:17.7968] Plugins::TIDAL::API::Async::__ANON__ (572) Error: 500 Internal Server Error

**Comment by philippe44** [comment]
the request
```
https://api.tidal.com/v1/mixes/daily/track?countryCode=US
```
Still gives me the "expected" answer

**Comment by michaelherger** [comment]
Really?!? I got the path wrong? How stupid am I?!? I double and tripple checked this several times... I guess that's what you get when you try to rush it because you forgot the power brick in the office 😠. Thanks for the confirmation! I'll fix that before I really run out of power.

**Comment by kronzo** [comment]
Closed too early?
My Mix is ​​still empty, I'm using the current version 6adaeba

**Comment by michaelherger** [comment]
Probably a caching issue. Results are cached for an hour. Can you try again, with `plugin.tidal=info` logging enabled. If it still doesn't work, please provide the server.log.

**Comment by kronzo** [comment]
Sorry, my mistake, I've got a wrong version. Now I see my 'My Mix', everything OK now.
